services:
  postgres:
    image: postgres:16-alpine
    container_name: order-orchestrator-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: order_orchestrator
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev@1234
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev -d order_orchestrator']
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: order-orchestrator-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev@1234
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data: